// GENERATED from TradingView's stock screener column picker (premium account,
// Oct 2026): every column in its "+" menu, in its categories and order, with
// each period / length variant TradingView's IDX scanner serves data for.
// Variant fields were checked against a live `/indonesia/scan` request.

import { ColumnFormat, ScreenerColumn } from './screener-config';

/** One entry in TradingView's column picker; its variants are periods/lengths. */
export type TvColumn = {
	/** TradingView's own column id, e.g. `NetIncome`. */
	id: string;
	label: string;
	variants: ScreenerColumn[];
};

export type TvCategory = {
	id: string;
	label: string;
	sections: { label?: string; columns: TvColumn[] }[];
};

type Variant = [
	field: string,
	sub?: string,
	format?: ColumnFormat,
	extra?: Pick<ScreenerColumn, 'displayField' | 'width'>,
];

const col = (
	id: string,
	label: string,
	format: ColumnFormat,
	variants: Variant[]
): TvColumn => ({
	id,
	label,
	variants: variants.map(([field, sub, fmt, extra]) => ({
		field,
		label,
		sub,
		format: fmt ?? format,
		...extra,
	})),
});

export const TV_CATEGORIES: TvCategory[] = [
	{
		id: 'securityInfo',
		label: 'Security info',
		sections: [
			{
				columns: [
					col('AnalystRating', 'Analyst rating', 'rating', [['AnalystRating', undefined, undefined, { displayField: 'AnalystRating.tr', width: 14 }]]),
					col('CfiCode', 'CFI classification', 'text', [['cfi_code']]),
					col('HighestIncomeCountry', 'Country of highest income', 'text', [['country_of_highest_income']]),
					col('Country', 'Country or region of registration', 'text', [['country', undefined, undefined, { displayField: 'country.tr' }]]),
					col('Cusip', 'CUSIP', 'text', [['cusip']]),
					col('Exchange', 'Exchange', 'text', [['exchange']]),
					col('SubMarket', 'Exchange market', 'text', [['submarket']]),
					col('Figi', 'FIGI', 'text', [['figi.exchange-level']]),
					col('FiscalPeriodEndDate', 'Fiscal period end date', 'date', [['fiscal_period_end_fq', 'FQ'], ['fiscal_period_end_fy', 'FY'], ['fiscal_period_end_fh', 'FH'], ['fiscal_period_end_current', 'Current']]),
					col('FloatShares', 'Free float %', 'percent', [['float_shares_percent_current']]),
					col('SharesFloat', 'Free float', 'auto', [['float_shares_outstanding_current']]),
					col('Index', 'Index', 'indexes', [['indexes', undefined, undefined, { width: 40 }]]),
					col('Industry', 'Industry', 'text', [['industry', undefined, undefined, { displayField: 'industry.tr', width: 28 }]]),
					col('IPODealAmount', 'IPO deal amount', 'auto', [['ipo_deal_amount_usd', 'USD']]),
					col('IPOOfferDate', 'IPO offer date', 'date', [['ipo_offer_date']]),
					col('IPOOfferPrice', 'IPO offer price', 'number', [['ipo_offer_price_usd', 'USD']]),
					col('Isin', 'ISIN', 'text', [['isin-displayed']]),
					col('NumberOfShareholders', 'Number of shareholders', 'auto', [['number_of_shareholders'], ['number_of_shareholders_fy', 'FY']]),
					col('IPOOfferPricePerformance', 'Offer price performance %', 'change', [['ipo_offer_price_performance']]),
					col('EarningsRecent', 'Recent earnings date', 'date', [['earnings_release_trading_date_fq']]),
					col('RecentFiscalPeriod', 'Recent fiscal period', 'text', [['fiscal_period_current', 'Current'], ['fiscal_period_fy', 'FY']]),
					col('Sector', 'Sector', 'text', [['sector', undefined, undefined, { displayField: 'sector.tr', width: 24 }]]),
					col('TargetPrice', 'Target price', 'price', [['price_target_1y', '1Y'], ['price_target_average', 'Average'], ['price_target_median', 'Median'], ['price_target_high', 'High'], ['price_target_low', 'Low']]),
					col('TargetPricePerformance', 'Target price performance %', 'change', [['price_target_1y_delta', '1Y']]),
					col('TotalSharesOutstanding', 'Total common shares outstanding', 'auto', [['total_shares_outstanding_current']]),
					col('EarningsUpcoming', 'Upcoming earnings date', 'date', [['earnings_release_next_trading_date_fq']]),
				],
			},
		],
	},
	{
		id: 'marketData',
		label: 'Market data',
		sections: [
			{
				label: 'Regular hours',
				columns: [
					col('AverageVolume', 'Average volume', 'volume', [['average_volume_10d_calc', '10D'], ['average_volume_30d_calc', '30D'], ['average_volume_60d_calc', '60D'], ['average_volume_90d_calc', '90D']]),
					col('Beta', 'Beta', 'number', [['beta_1_year', '1Y'], ['beta_3_year', '3Y'], ['beta_5_year', '5Y']]),
					col('ChangeFromOpen', 'Change from open %', 'change', [['change_from_open']]),
					col('ChangeFromOpenAbs', 'Change from open', 'change', [['change_from_open_abs']]),
					col('Gap', 'Gap %', 'change', [['gap']]),
					col('High', 'High', 'price', [['high']]),
					col('Low', 'Low', 'price', [['low']]),
					col('Open', 'Open', 'price', [['open']]),
					col('Performance', 'Performance %', 'change', [['Perf.5D', '5D'], ['Perf.W', '1W'], ['Perf.1M', '1M'], ['Perf.3M', '3M'], ['Perf.6M', '6M'], ['Perf.YTD', 'YTD'], ['Perf.Y', '1Y'], ['Perf.3Y', '3Y'], ['Perf.5Y', '5Y'], ['Perf.10Y', '10Y'], ['Perf.All', 'All Time']]),
					col('Price', 'Price', 'price', [['close']]),
					col('PriceAvgVolume', 'Price × average volume', 'money', [['AvgValue.Traded_10d', '10D'], ['AvgValue.Traded_30d', '30D'], ['AvgValue.Traded_60d', '60D'], ['AvgValue.Traded_90d', '90D']]),
					col('VolumePrice', 'Price × volume (turnover)', 'money', [['Value.Traded']]),
					col('Change', 'Price change %', 'change', [['change']]),
					col('ChangeAbs', 'Price change', 'change', [['change_abs']]),
					col('RelativeVolume', 'Relative volume', 'number', [['relative_volume_10d_calc', '10D']]),
					col('RelativeVolumeAtTime', 'Relative volume at time', 'number', [['relative_volume_intraday|5']]),
					col('Volatility', 'Volatility', 'percent', [['Volatility.D', '1D'], ['Volatility.W', '1W'], ['Volatility.M', '1M']]),
					col('Volume', 'Volume', 'volume', [['volume']]),
					col('VolumeChange', 'Volume change %', 'change', [['volume_change']]),
					col('VolumeChangeAbs', 'Volume change', 'volume', [['volume_change_abs']]),
				],
			},
			{
				label: 'Extended hours',
				columns: [
					col('PostMarketChange', 'Post-market change %', 'change', [['postmarket_change']]),
					col('PostMarketChangeAbs', 'Post-market change', 'change', [['postmarket_change_abs']]),
					col('PostMarketHigh', 'Post-market high', 'price', [['postmarket_high']]),
					col('PostMarketLow', 'Post-market low', 'price', [['postmarket_low']]),
					col('PostMarketOpen', 'Post-market open', 'price', [['postmarket_open']]),
					col('PostMarketClose', 'Post-market price', 'price', [['postmarket_close']]),
					col('PostMarketVolume', 'Post-market volume', 'volume', [['postmarket_volume']]),
					col('PreMarketChange', 'Pre-market change %', 'change', [['premarket_change']]),
					col('PreMarketChangeAbs', 'Pre-market change', 'change', [['premarket_change_abs']]),
					col('PreMarketChangeFromOpen', 'Pre-market change from open %', 'change', [['premarket_change_from_open']]),
					col('PreMarketChangeFromOpenAbs', 'Pre-market change from open', 'change', [['premarket_change_from_open_abs']]),
					col('PreMarketGap', 'Pre-market gap %', 'change', [['premarket_gap']]),
					col('PreMarketHigh', 'Pre-market high', 'price', [['premarket_high']]),
					col('PreMarketLow', 'Pre-market low', 'price', [['premarket_low']]),
					col('PreMarketOpen', 'Pre-market open', 'price', [['premarket_open']]),
					col('PreMarketClose', 'Pre-market price', 'price', [['premarket_close']]),
					col('PreMarketVolume', 'Pre-market volume', 'volume', [['premarket_volume']]),
				],
			},
		],
	},
	{
		id: 'technicals',
		label: 'Technicals',
		sections: [
			{
				columns: [
					col('Aroon', 'Aroon', 'number', [['Aroon.Up', 'Up 14'], ['Aroon.Down', 'Down 14']]),
					col('AverageDailyRange', 'Average daily range', 'number', [['ADR', '14']]),
					col('AverageDayRangePercent', 'Average daily range %', 'percent', [['ADRP', '14']]),
					col('AverageDirectionalIndex', 'Average directional index', 'number', [['ADX', '14'], ['ADX_9', '9'], ['ADX_20', '20'], ['ADX_50', '50'], ['ADX_100', '100']]),
					col('AverageTrueRange', 'Average true range', 'number', [['ATR', '14']]),
					col('AverageTrueRangePercent', 'Average true range %', 'percent', [['ATRP', '14']]),
					col('AwesomeOscillator', 'Awesome oscillator', 'number', [['AO']]),
					col('BollingerBands', 'Bollinger bands', 'number', [['BB.upper', 'Upper 20'], ['BB.basis', 'Basis 20'], ['BB.lower', 'Lower 20'], ['BB.upper_50', 'Upper 50'], ['BB.basis_50', 'Basis 50'], ['BB.lower_50', 'Lower 50']]),
					col('BBPower', 'Bull bear power', 'number', [['BBPower', '13']]),
					col('Pattern', 'Candlestick pattern', 'patterns', [['candlestick_patterns_1D', '1D', undefined, { width: 24 }]]),
					col('ChaikinMoneyFlow', 'Chaikin money flow', 'number', [['ChaikinMoneyFlow', '20']]),
					col('CommodityChannelIndex', 'Commodity channel index', 'number', [['CCI20', '20']]),
					col('DirectionalMovementIndex', 'Directional movement index', 'number', [['ADX+DI', '+DI 14'], ['ADX-DI', '−DI 14']]),
					col('DonchianChannels', 'Donchian channels', 'number', [['DonchCh20.Upper', 'Upper 20'], ['DonchCh20.Middle', 'Middle 20'], ['DonchCh20.Lower', 'Lower 20']]),
					col('Ema', 'Exponential moving average', 'number', [['EMA2', '2'], ['EMA3', '3'], ['EMA5', '5'], ['EMA6', '6'], ['EMA7', '7'], ['EMA8', '8'], ['EMA9', '9'], ['EMA10', '10'], ['EMA12', '12'], ['EMA13', '13'], ['EMA14', '14'], ['EMA15', '15'], ['EMA20', '20'], ['EMA21', '21'], ['EMA25', '25'], ['EMA26', '26'], ['EMA30', '30'], ['EMA34', '34'], ['EMA40', '40'], ['EMA50', '50'], ['EMA55', '55'], ['EMA60', '60'], ['EMA75', '75'], ['EMA89', '89'], ['EMA100', '100'], ['EMA120', '120'], ['EMA144', '144'], ['EMA150', '150'], ['EMA200', '200'], ['EMA250', '250'], ['EMA300', '300']]),
					col('HullMovingAverage', 'Hull moving average', 'number', [['HullMA9', '9'], ['HullMA20', '20'], ['HullMA200', '200']]),
					col('IchimokuCloud', 'Ichimoku cloud', 'number', [['Ichimoku.BLine', 'Base line'], ['Ichimoku.CLine', 'Conversion line'], ['Ichimoku.Lead1', 'Leading span A'], ['Ichimoku.Lead2', 'Leading span B']]),
					col('KeltnerChannels', 'Keltner channels', 'number', [['KltChnl.upper', 'Upper 20'], ['KltChnl.basis', 'Basis 20'], ['KltChnl.lower', 'Lower 20']]),
					col('Momentum', 'Momentum', 'number', [['Mom', '10'], ['Mom_14', '14']]),
					col('MoneyFlow', 'Money flow index', 'number', [['MoneyFlow', '14']]),
					col('Macd', 'Moving average convergence divergence', 'number', [['MACD.macd', 'Level'], ['MACD.signal', 'Signal'], ['MACD.hist', 'Histogram']]),
					col('RatingMa', 'Moving averages rating', 'rating', [['MARating_1D', '1D', undefined, { displayField: 'MARating_1D.tr' }]]),
					col('RatingOscillators', 'Oscillators rating', 'rating', [['OsRating_1D', '1D', undefined, { displayField: 'OsRating_1D.tr' }]]),
					col('Psar', 'Parabolic SAR', 'number', [['P.SAR']]),
					col('PivotCamarilla', 'Pivot points Camarilla', 'number', [['Pivot.M.Camarilla.Middle', 'P'], ['Pivot.M.Camarilla.R1', 'R1'], ['Pivot.M.Camarilla.R2', 'R2'], ['Pivot.M.Camarilla.R3', 'R3'], ['Pivot.M.Camarilla.S1', 'S1'], ['Pivot.M.Camarilla.S2', 'S2'], ['Pivot.M.Camarilla.S3', 'S3']]),
					col('PivotClassic', 'Pivot points Classic', 'number', [['Pivot.M.Classic.Middle', 'P'], ['Pivot.M.Classic.R1', 'R1'], ['Pivot.M.Classic.R2', 'R2'], ['Pivot.M.Classic.R3', 'R3'], ['Pivot.M.Classic.S1', 'S1'], ['Pivot.M.Classic.S2', 'S2'], ['Pivot.M.Classic.S3', 'S3']]),
					col('PivotDemark', 'Pivot points DeMark', 'number', [['Pivot.M.Demark.Middle', 'P'], ['Pivot.M.Demark.R1', 'R1'], ['Pivot.M.Demark.S1', 'S1']]),
					col('PivotFibonacci', 'Pivot points Fibonacci', 'number', [['Pivot.M.Fibonacci.Middle', 'P'], ['Pivot.M.Fibonacci.R1', 'R1'], ['Pivot.M.Fibonacci.R2', 'R2'], ['Pivot.M.Fibonacci.R3', 'R3'], ['Pivot.M.Fibonacci.S1', 'S1'], ['Pivot.M.Fibonacci.S2', 'S2'], ['Pivot.M.Fibonacci.S3', 'S3']]),
					col('PivotWoodie', 'Pivot points Woodie', 'number', [['Pivot.M.Woodie.Middle', 'P'], ['Pivot.M.Woodie.R1', 'R1'], ['Pivot.M.Woodie.R2', 'R2'], ['Pivot.M.Woodie.R3', 'R3'], ['Pivot.M.Woodie.S1', 'S1'], ['Pivot.M.Woodie.S2', 'S2'], ['Pivot.M.Woodie.S3', 'S3']]),
					col('RateOfChange', 'Rate of change', 'number', [['ROC', '9']]),
					col('RelativeStrengthIndex', 'Relative strength index', 'number', [['RSI', '14'], ['RSI2', '2'], ['RSI3', '3'], ['RSI4', '4'], ['RSI5', '5'], ['RSI7', '7'], ['RSI9', '9'], ['RSI10', '10'], ['RSI20', '20'], ['RSI21', '21'], ['RSI30', '30']]),
					col('Ma', 'Simple moving average', 'number', [['SMA2', '2'], ['SMA3', '3'], ['SMA5', '5'], ['SMA6', '6'], ['SMA7', '7'], ['SMA8', '8'], ['SMA9', '9'], ['SMA10', '10'], ['SMA12', '12'], ['SMA13', '13'], ['SMA14', '14'], ['SMA15', '15'], ['SMA20', '20'], ['SMA21', '21'], ['SMA25', '25'], ['SMA26', '26'], ['SMA30', '30'], ['SMA34', '34'], ['SMA40', '40'], ['SMA50', '50'], ['SMA55', '55'], ['SMA60', '60'], ['SMA75', '75'], ['SMA89', '89'], ['SMA100', '100'], ['SMA120', '120'], ['SMA144', '144'], ['SMA150', '150'], ['SMA200', '200'], ['SMA250', '250'], ['SMA300', '300']]),
					col('Stochastic', 'Stochastic', 'number', [['Stoch.K', '%K 14, 3, 3'], ['Stoch.D', '%D 14, 3, 3'], ['Stoch.K_5_3_3', '%K 5, 3, 3'], ['Stoch.D_5_3_3', '%D 5, 3, 3'], ['Stoch.K_6_3_3', '%K 6, 3, 3'], ['Stoch.D_6_3_3', '%D 6, 3, 3'], ['Stoch.K_8_3_3', '%K 8, 3, 3'], ['Stoch.D_8_3_3', '%D 8, 3, 3'], ['Stoch.K_14_1_3', '%K 14, 1, 3'], ['Stoch.D_14_1_3', '%D 14, 1, 3']]),
					col('StochasticRsi', 'Stochastic RSI', 'number', [['Stoch.RSI.K', '%K'], ['Stoch.RSI.D', '%D']]),
					col('TechnicalRating', 'Technical rating', 'rating', [['TechRating_1D', '1D', undefined, { displayField: 'TechRating_1D.tr' }]]),
					col('UltimateOscillator', 'Ultimate oscillator', 'number', [['UO', '7, 14, 28']]),
					col('VolumeWeightedAveragePrice', 'Volume-weighted average price', 'number', [['VWAP']]),
					col('VolumeWeightedMovingAverage', 'Volume-weighted moving average', 'number', [['VWMA', '20']]),
					col('WilliamsPercentRange', 'Williams percent range', 'number', [['W.R', '14']]),
				],
			},
		],
	},
	{
		id: 'financials',
		label: 'Financials',
		sections: [
			{
				label: 'Income statement',
				columns: [
					col('BasicEps', 'Basic earnings per share', 'fundamental', [['earnings_per_share_basic_ttm', 'TTM'], ['earnings_per_share_basic_fq', 'FQ'], ['earnings_per_share_basic_fy', 'FY'], ['earnings_per_share_basic_fh', 'FH']]),
					col('CostOfSalesEstimate', 'Cost of sales estimate', 'fundamental', [['cost_of_goods_estimate_fy', 'FY']]),
					col('DividendsPerShareEstimate', 'Dividends per share estimate', 'fundamental', [['dps_estimate_fq', 'FQ'], ['dps_estimate_fy', 'FY']]),
					col('EpsDiluted', 'Earnings per share diluted', 'fundamental', [['earnings_per_share_diluted_ttm', 'TTM'], ['earnings_per_share_diluted_fq', 'FQ'], ['earnings_per_share_diluted_fy', 'FY'], ['earnings_per_share_diluted_fh', 'FH']]),
					col('EpsForecast', 'Earnings per share estimate', 'fundamental', [['earnings_per_share_forecast_next_fq', 'FQ'], ['earnings_per_share_forecast_next_fy', 'FY'], ['earnings_per_share_forecast_next_fh', 'FH']]),
					col('ReportedEps', 'Earnings per share reported', 'fundamental', [['earnings_per_share_fq', 'FQ'], ['earnings_per_share_fy', 'FY'], ['earnings_per_share_fh', 'FH']]),
					col('Ebitda', 'EBITDA', 'fundamental', [['ebitda_ttm', 'TTM'], ['ebitda_fq', 'FQ'], ['ebitda_fy', 'FY'], ['ebitda_fh', 'FH']]),
					col('EbitdaEstimate', 'EBITDA estimate', 'fundamental', [['ebitda_estimate_fq', 'FQ'], ['ebitda_estimate_fy', 'FY'], ['ebitda_estimate_fh', 'FH'], ['ebitda_estimate_ntm', 'NTM']]),
					col('EbitEstimate', 'EBIT estimate', 'fundamental', [['ebit_estimate_fq', 'FQ'], ['ebit_estimate_fy', 'FY'], ['ebit_estimate_fh', 'FH'], ['ebit_estimate_ntm', 'NTM']]),
					col('GrossProfit', 'Gross profit', 'fundamental', [['gross_profit_ttm', 'TTM'], ['gross_profit_fq', 'FQ'], ['gross_profit_fy', 'FY'], ['gross_profit_fh', 'FH']]),
					col('GrossProfitEstimate', 'Gross profit estimate', 'fundamental', [['gross_profit_estimate_fy', 'FY']]),
					col('NetIncome', 'Net income', 'fundamental', [['net_income_ttm', 'TTM'], ['net_income_fq', 'FQ'], ['net_income_fy', 'FY'], ['net_income_fh', 'FH']]),
					col('NetIncomeEstimate', 'Net income estimate', 'fundamental', [['net_income_estimate_fq', 'FQ'], ['net_income_estimate_fy', 'FY'], ['net_income_estimate_fh', 'FH'], ['net_income_estimate_ntm', 'NTM']]),
					col('NetIncomeFromContinuingOperations', 'Net income from continuing operations', 'fundamental', [['income_from_cont_ops_ttm', 'TTM'], ['income_from_cont_ops_fq', 'FQ'], ['income_from_cont_ops_fy', 'FY']]),
					col('NetRevenue', 'Net revenue', 'fundamental', [['net_revenue_ttm', 'TTM'], ['net_revenue_fq', 'FQ'], ['net_revenue_fy', 'FY']]),
					col('NetRevenueAfterProvision', 'Net revenue after provision', 'fundamental', [['net_revenue_after_provision_ttm', 'TTM'], ['net_revenue_after_provision_fq', 'FQ'], ['net_revenue_after_provision_fy', 'FY']]),
					col('OperatingIncome', 'Operating income', 'fundamental', [['oper_income_ttm', 'TTM'], ['oper_income_fq', 'FQ'], ['oper_income_fy', 'FY'], ['oper_income_fh', 'FH']]),
					col('ResearchNDevelopment', 'Research and development', 'fundamental', [['neg_research_and_dev_ttm', 'TTM'], ['neg_research_and_dev_fq', 'FQ'], ['neg_research_and_dev_fy', 'FY'], ['neg_research_and_dev_fh', 'FH']]),
					col('ResearchNDevelopmentEstimate', 'Research and development estimate', 'fundamental', [['research_and_dev_estimate_fy', 'FY']]),
					col('RevenueEstimate', 'Revenue estimate', 'fundamental', [['revenue_forecast_next_fq', 'FQ'], ['revenue_forecast_next_fy', 'FY'], ['revenue_forecast_next_fh', 'FH']]),
					col('SellingGeneralNAdminExpensesEstimate', 'Selling, general, and admin expenses estimate', 'fundamental', [['sell_gen_admin_exp_total_estimate_fy', 'FY']]),
					col('TotalRevenue', 'Total revenue', 'fundamental', [['total_revenue_ttm', 'TTM'], ['total_revenue_fq', 'FQ'], ['total_revenue_fy', 'FY'], ['total_revenue_fh', 'FH']]),
				],
			},
			{
				label: 'Cash flow',
				columns: [
					col('CapitalExpenditures', 'Capital expenditures', 'fundamental', [['neg_capital_expenditures_ttm', 'TTM'], ['neg_capital_expenditures_fq', 'FQ'], ['neg_capital_expenditures_fy', 'FY'], ['neg_capital_expenditures_fh', 'FH']]),
					col('CapitalExpendituresEstimate', 'Capital expenditures estimate', 'fundamental', [['capital_expenditures_estimate_fq', 'FQ'], ['capital_expenditures_estimate_fy', 'FY'], ['capital_expenditures_estimate_ntm', 'NTM']]),
					col('CashFromFinancing', 'Cash flow from financing activities', 'fundamental', [['cash_f_financing_activities_ttm', 'TTM'], ['cash_f_financing_activities_fq', 'FQ'], ['cash_f_financing_activities_fy', 'FY'], ['cash_f_financing_activities_fh', 'FH']]),
					col('CashFromFinancingEstimate', 'Cash flow from financing activities estimate', 'fundamental', [['cash_f_financing_activities_estimate_fy', 'FY']]),
					col('CashFromInvesting', 'Cash flow from investing activities', 'fundamental', [['cash_f_investing_activities_ttm', 'TTM'], ['cash_f_investing_activities_fq', 'FQ'], ['cash_f_investing_activities_fy', 'FY'], ['cash_f_investing_activities_fh', 'FH']]),
					col('CashFromInvestingEstimate', 'Cash flow from investing activities estimate', 'fundamental', [['cash_f_investing_activities_estimate_fy', 'FY']]),
					col('CashFromOperating', 'Cash flow from operating activities', 'fundamental', [['cash_f_operating_activities_ttm', 'TTM'], ['cash_f_operating_activities_fq', 'FQ'], ['cash_f_operating_activities_fy', 'FY'], ['cash_f_operating_activities_fh', 'FH']]),
					col('CashFromOperatingEstimate', 'Cash flow from operating activities estimate', 'fundamental', [['cash_f_operating_activities_estimate_fq', 'FQ'], ['cash_f_operating_activities_estimate_fy', 'FY']]),
					col('FreeCashFlow', 'Free cash flow', 'fundamental', [['free_cash_flow_ttm', 'TTM'], ['free_cash_flow_fq', 'FQ'], ['free_cash_flow_fy', 'FY'], ['free_cash_flow_fh', 'FH']]),
					col('FreeCashFlowEstimate', 'Free cash flow estimate', 'fundamental', [['free_cash_flow_estimate_fy', 'FY']]),
				],
			},
			{
				label: 'Balance sheet',
				columns: [
					col('CashNEquivalents', 'Cash and equivalents', 'fundamental', [['cash_n_equivalents_fq', 'FQ'], ['cash_n_equivalents_fy', 'FY']]),
					col('CashNShortTermInvest', 'Cash and short-term investments', 'fundamental', [['cash_n_short_term_invest_fq', 'FQ'], ['cash_n_short_term_invest_fy', 'FY']]),
					col('CashNShortTermInvestEstimate', 'Cash and short term investments estimate', 'fundamental', [['cash_n_short_term_invest_estimate_fy', 'FY']]),
					col('Goodwill', 'Goodwill (net)', 'fundamental', [['goodwill_fq', 'FQ'], ['goodwill_fy', 'FY']]),
					col('LTDebt', 'Long-term debt', 'fundamental', [['long_term_debt_fq', 'FQ'], ['long_term_debt_fy', 'FY']]),
					col('NetDebt', 'Net debt', 'fundamental', [['net_debt_fq', 'FQ'], ['net_debt_fy', 'FY']]),
					col('STDebt', 'Short-term debt', 'fundamental', [['short_term_debt_fq', 'FQ'], ['short_term_debt_fy', 'FY']]),
					col('TotalAssets', 'Total assets', 'fundamental', [['total_assets_fq', 'FQ'], ['total_assets_fy', 'FY']]),
					col('TotalAssetsEstimate', 'Total assets estimate', 'fundamental', [['total_assets_estimate_fq', 'FQ'], ['total_assets_estimate_fy', 'FY']]),
					col('TotalCurrentAssets', 'Total current assets', 'fundamental', [['total_current_assets_fq', 'FQ'], ['total_current_assets_fy', 'FY']]),
					col('TotalCurrentLiabilities', 'Total current liabilities', 'fundamental', [['total_current_liabilities_fq', 'FQ'], ['total_current_liabilities_fy', 'FY']]),
					col('TotalDebt', 'Total debt', 'fundamental', [['total_debt_fq', 'FQ'], ['total_debt_fy', 'FY']]),
					col('TotalDebtEstimate', 'Total debt estimate', 'fundamental', [['total_debt_estimate_fy', 'FY']]),
					col('TotalEquity', 'Total equity', 'fundamental', [['total_equity_fq', 'FQ'], ['total_equity_fy', 'FY']]),
					col('TotalLiabilities', 'Total liabilities', 'fundamental', [['total_liabilities_fq', 'FQ'], ['total_liabilities_fy', 'FY']]),
				],
			},
		],
	},
	{
		id: 'valuation',
		label: 'Valuation',
		sections: [
			{
				columns: [
					col('EarningsYield', 'Earnings yield %', 'percent', [['earnings_yield']]),
					col('Ev', 'Enterprise value', 'money', [['enterprise_value_current']]),
					col('EvToEbitda', 'Enterprise value to EBITDA ratio', 'number', [['enterprise_value_ebitda_ttm', 'TTM'], ['enterprise_value_ebitda_current', 'Current']]),
					col('EvToEbitdaForward', 'Enterprise value to EBITDA ratio forward', 'number', [['enterprise_value_ebitda_fwd']]),
					col('EvToEbit', 'Enterprise value to EBIT ratio', 'number', [['enterprise_value_to_ebit_ttm', 'TTM']]),
					col('EvToEbitForward', 'Enterprise value to EBIT ratio forward', 'number', [['enterprise_value_ebit_fwd']]),
					col('EvToFreeCashFlow', 'Enterprise value to free cash flow', 'number', [['enterprise_value_to_free_cash_flow_ttm', 'TTM']]),
					col('EvToGrossProfit', 'Enterprise value to gross profit ratio', 'number', [['enterprise_value_to_gross_profit_ttm', 'TTM']]),
					col('EvToRevenue', 'Enterprise value to revenue ratio', 'number', [['enterprise_value_to_revenue_ttm', 'TTM']]),
					col('EvToRevenueForward', 'Enterprise value to revenue ratio forward', 'number', [['enterprise_value_sales_fwd']]),
					col('MarketCap', 'Market capitalization', 'money', [['market_cap_basic', undefined, undefined, { width: 20 }]]),
					col('MarketCapPerf', 'Market capitalization performance %', 'change', [['Perf.1W.MarketCap', '1W'], ['Perf.1M.MarketCap', '1M'], ['Perf.3M.MarketCap', '3M'], ['Perf.6M.MarketCap', '6M'], ['Perf.YTD.MarketCap', 'YTD'], ['Perf.1Y.MarketCap', '1Y'], ['Perf.5Y.MarketCap', '5Y']]),
					col('PriceToBook', 'Price to book ratio', 'number', [['price_book_fq']]),
					col('PriceToBookForward', 'Price to book ratio forward', 'number', [['price_book_fwd']]),
					col('PriceToCashFlow', 'Price to cash flow ratio', 'number', [['price_to_cash_f_operating_activities_ttm']]),
					col('PriceToCashRatio', 'Price to cash ratio', 'number', [['price_to_cash_ratio']]),
					col('PriceToEarnings', 'Price to earnings ratio', 'number', [['price_earnings_ttm']]),
					col('PriceToEarningsForward', 'Price to earnings ratio forward', 'number', [['price_earnings_fwd']]),
					col('ForwardPriceToEarnings', 'Price to earnings ratio forward Non-GAAP', 'number', [['non_gaap_price_to_earnings_per_share_forecast_next_fy', 'FY']]),
					col('PriceToEarningsToGrowth', 'Price to earning to growth', 'number', [['price_earnings_growth_ttm', 'TTM']]),
					col('PriceToFreeCashFlow', 'Price to free cash flow ratio', 'number', [['price_free_cash_flow_ttm']]),
					col('PriceToNetWorkingCapital', 'Price to net working capital', 'number', [['price_to_working_capital_fq']]),
					col('PriceToSales', 'Price to sales ratio', 'number', [['price_sales_current']]),
					col('PriceToSalesForward', 'Price to sales ratio forward', 'number', [['price_sales_fwd']]),
				],
			},
		],
	},
	{
		id: 'growth',
		label: 'Growth',
		sections: [
			{
				columns: [
					col('CapexGrowth', 'Capital expenditures growth %', 'change', [['capital_expenditures_yoy_growth_ttm', 'TTM YoY'], ['capital_expenditures_yoy_growth_fy', 'FY YoY'], ['capital_expenditures_yoy_growth_fq', 'FQ YoY'], ['capital_expenditures_qoq_growth_fq', 'FQ QoQ']]),
					col('EpsDilutedGrowth', 'Earnings per share diluted growth %', 'change', [['earnings_per_share_diluted_yoy_growth_ttm', 'TTM YoY'], ['earnings_per_share_diluted_yoy_growth_fy', 'FY YoY'], ['earnings_per_share_diluted_yoy_growth_fq', 'FQ YoY'], ['earnings_per_share_diluted_qoq_growth_fq', 'FQ QoQ'], ['earnings_per_share_diluted_5y_growth_fy', 'FY 5Y']]),
					col('EbitdaGrowth', 'EBITDA growth %', 'change', [['ebitda_yoy_growth_ttm', 'TTM YoY'], ['ebitda_yoy_growth_fy', 'FY YoY'], ['ebitda_yoy_growth_fq', 'FQ YoY'], ['ebitda_qoq_growth_fq', 'FQ QoQ']]),
					col('FreeCashFlowGrowth', 'Free cash flow growth %', 'change', [['free_cash_flow_yoy_growth_ttm', 'TTM YoY'], ['free_cash_flow_yoy_growth_fy', 'FY YoY'], ['free_cash_flow_yoy_growth_fq', 'FQ YoY'], ['free_cash_flow_qoq_growth_fq', 'FQ QoQ'], ['free_cash_flow_cagr_5y', '5Y CAGR']]),
					col('GrossProfitGrowth', 'Gross profit growth %', 'change', [['gross_profit_yoy_growth_ttm', 'TTM YoY'], ['gross_profit_yoy_growth_fy', 'FY YoY'], ['gross_profit_yoy_growth_fq', 'FQ YoY'], ['gross_profit_qoq_growth_fq', 'FQ QoQ']]),
					col('NetIncomeGrowth', 'Net income growth %', 'change', [['net_income_yoy_growth_ttm', 'TTM YoY'], ['net_income_yoy_growth_fy', 'FY YoY'], ['net_income_yoy_growth_fq', 'FQ YoY'], ['net_income_qoq_growth_fq', 'FQ QoQ'], ['net_income_cagr_5y', '5Y CAGR']]),
					col('RevenueGrowth', 'Revenue growth %', 'change', [['total_revenue_yoy_growth_ttm', 'TTM YoY'], ['total_revenue_yoy_growth_fy', 'FY YoY'], ['total_revenue_yoy_growth_fq', 'FQ YoY'], ['total_revenue_qoq_growth_fq', 'FQ QoQ'], ['total_revenue_cagr_5y', '5Y CAGR'], ['total_revenue_5y_growth_fy', 'FY 5Y']]),
					col('TotalAssetsGrowth', 'Total assets growth %', 'change', [['total_assets_yoy_growth_fy', 'FY YoY'], ['total_assets_yoy_growth_fq', 'FQ YoY'], ['total_assets_qoq_growth_fq', 'FQ QoQ']]),
					col('TotalDebtGrowth', 'Total debt growth %', 'change', [['total_debt_yoy_growth_fy', 'FY YoY'], ['total_debt_yoy_growth_fq', 'FQ YoY'], ['total_debt_qoq_growth_fq', 'FQ QoQ']]),
				],
			},
		],
	},
	{
		id: 'marginsAndRatios',
		label: 'Margins',
		sections: [
			{
				columns: [
					col('AltmanZScore', 'Altman Z-score', 'number', [['altman_z_score_ttm', 'TTM'], ['altman_z_score_fy', 'FY']]),
					col('AssetsToEquityRatio', 'Assets to equity ratio', 'number', [['total_assets_to_equity_fq', 'FQ'], ['total_assets_to_equity_fy', 'FY']]),
					col('AssetsTurnover', 'Asset turnover', 'number', [['asset_turnover_fy', 'FY'], ['asset_turnover_current', 'Current']]),
					col('BookPerShare', 'Book value per share', 'fundamental', [['book_value_per_share_fq', 'FQ'], ['book_value_per_share_fy', 'FY'], ['book_value_per_share_fh', 'FH'], ['book_value_per_share_current', 'Current']]),
					col('BookPerShareEstimate', 'Book value per share estimate', 'fundamental', [['book_value_per_share_estimate_fq', 'FQ'], ['book_value_per_share_estimate_fy', 'FY']]),
					col('BuybackYield', 'Buyback yield %', 'percent', [['buyback_yield']]),
					col('CapExPerShare', 'Capital expenditures per share', 'fundamental', [['capex_per_share_ttm', 'TTM'], ['capex_per_share_fq', 'FQ'], ['capex_per_share_fy', 'FY'], ['capex_per_share_fh', 'FH'], ['capex_per_share_current', 'Current']]),
					col('CashDividendCoverageRatio', 'Cash dividend coverage ratio', 'number', [['cash_dividend_coverage_ratio_ttm', 'TTM'], ['cash_dividend_coverage_ratio_fy', 'FY']]),
					col('CashPerShare', 'Cash per share', 'fundamental', [['cash_per_share_fq', 'FQ'], ['cash_per_share_fy', 'FY'], ['cash_per_share_fh', 'FH'], ['cash_per_share_current', 'Current']]),
					col('CashRatio', 'Cash ratio', 'number', [['cash_n_short_term_invest_to_total_current_liabilities_fq', 'FQ'], ['cash_n_short_term_invest_to_total_current_liabilities_fy', 'FY']]),
					col('CashToDebt', 'Cash to debt ratio', 'number', [['cash_n_short_term_invest_to_total_debt_fq', 'FQ'], ['cash_n_short_term_invest_to_total_debt_fy', 'FY']]),
					col('CurrentRatio', 'Current ratio', 'number', [['current_ratio_fq', 'FQ'], ['current_ratio_fy', 'FY'], ['current_ratio_current', 'Current']]),
					col('DebtToAssets', 'Debt to assets ratio', 'number', [['debt_to_asset_fq', 'FQ'], ['debt_to_asset_fy', 'FY']]),
					col('DebtToEbitda', 'Debt to EBITDA ratio', 'number', [['total_debt_to_ebitda_fq', 'FQ'], ['total_debt_to_ebitda_fy', 'FY']]),
					col('DebtToEquityRatio', 'Debt to equity ratio', 'number', [['debt_to_equity_fq', 'FQ'], ['debt_to_equity_fy', 'FY']]),
					col('DebtToRevenueRatio', 'Debt to revenue ratio', 'number', [['debt_to_revenue_ttm', 'TTM'], ['debt_to_revenue_fy', 'FY']]),
					col('EbitdaInterestCoverage', 'EBITDA interest coverage', 'number', [['ebitda_interst_cover_ttm', 'TTM'], ['ebitda_interst_cover_fy', 'FY']]),
					col('EbitdaLessCapexInterestCoverage', 'EBITDA less CapEx interest coverage', 'number', [['ebitda_less_capex_interst_cover_ttm', 'TTM'], ['ebitda_less_capex_interst_cover_fy', 'FY']]),
					col('EBITDAMargin', 'EBITDA margin %', 'percent', [['ebitda_margin_ttm', 'TTM'], ['ebitda_margin_fy', 'FY']]),
					col('EbitdaPerEmployee', 'EBITDA per employee', 'fundamental', [['ebitda_per_employee_fy', 'FY']]),
					col('EBITDAPerShare', 'EBITDA per share', 'fundamental', [['ebitda_per_share_ttm', 'TTM'], ['ebitda_per_share_fq', 'FQ'], ['ebitda_per_share_fy', 'FY'], ['ebitda_per_share_fh', 'FH'], ['ebitda_per_share_current', 'Current']]),
					col('EBITPerShare', 'EBIT per share', 'fundamental', [['ebit_per_share_ttm', 'TTM'], ['ebit_per_share_fq', 'FQ'], ['ebit_per_share_fy', 'FY'], ['ebit_per_share_fh', 'FH'], ['ebit_per_share_current', 'Current']]),
					col('EffectiveInterestRateOnDebt', 'Effective interest rate on debt %', 'percent', [['effective_interest_rate_on_debt_ttm', 'TTM'], ['effective_interest_rate_on_debt_fy', 'FY']]),
					col('EquityToAsset', 'Equity to assets ratio', 'number', [['shrhldrs_equity_to_total_assets_fq', 'FQ'], ['shrhldrs_equity_to_total_assets_fy', 'FY']]),
					col('FixedAssetsTurnover', 'Fixed assets turnover', 'number', [['fixed_assets_turnover_fq', 'FQ'], ['fixed_assets_turnover_fy', 'FY']]),
					col('FreeCashFlowMargin', 'Free cash flow margin %', 'percent', [['free_cash_flow_margin_ttm', 'TTM'], ['free_cash_flow_margin_fy', 'FY']]),
					col('FreeCashFlowPerEmployee', 'Free cash flow per employee', 'fundamental', [['free_cash_flow_per_employee_fy', 'FY']]),
					col('FreeCashFlowPerShare', 'Free cash flow per share', 'fundamental', [['free_cash_flow_per_share_ttm', 'TTM'], ['free_cash_flow_per_share_fq', 'FQ'], ['free_cash_flow_per_share_fy', 'FY'], ['free_cash_flow_per_share_fh', 'FH'], ['free_cash_flow_per_share_current', 'Current']]),
					col('GrahamsNumber', 'Graham\'s number', 'moneyPrecise', [['graham_numbers_ttm', 'TTM'], ['graham_numbers_fy', 'FY']]),
					col('GrossMargin', 'Gross margin %', 'percent', [['gross_margin_ttm', 'TTM'], ['gross_margin_fy', 'FY']]),
					col('InterestCoverage', 'Interest coverage', 'number', [['interst_cover_ttm', 'TTM'], ['interst_cover_fy', 'FY']]),
					col('InventoryTurnover', 'Inventory turnover', 'number', [['invent_turnover_fy', 'FY'], ['invent_turnover_current', 'Current']]),
					col('NCAVPS', 'Net current asset value per share', 'fundamental', [['ncavps_ratio_fq', 'FQ'], ['ncavps_ratio_fy', 'FY'], ['ncavps_ratio_fh', 'FH'], ['ncavps_ratio_current', 'Current']]),
					col('NetDebtToEbitda', 'Net debt to EBITDA ratio', 'number', [['net_debt_to_ebitda_fq', 'FQ'], ['net_debt_to_ebitda_fy', 'FY']]),
					col('NetIncomePerEmployee', 'Net income per employee', 'fundamental', [['net_income_per_employee_fy', 'FY']]),
					col('NetMargin', 'Net margin %', 'percent', [['net_margin_ttm', 'TTM'], ['net_margin_fy', 'FY']]),
					col('NumberOfEmployees', 'Number of employees', 'auto', [['number_of_employees'], ['number_of_employees_fy', 'FY']]),
					col('OperatingCashFlowPerShare', 'Operating cash flow per share', 'fundamental', [['operating_cash_flow_per_share_ttm', 'TTM'], ['operating_cash_flow_per_share_fq', 'FQ'], ['operating_cash_flow_per_share_fy', 'FY'], ['operating_cash_flow_per_share_fh', 'FH'], ['operating_cash_flow_per_share_current', 'Current']]),
					col('OperatingIncomePerEmployee', 'Operating income per employee', 'fundamental', [['oper_income_per_employee_fy', 'FY']]),
					col('OperatingMargin', 'Operating margin %', 'percent', [['operating_margin_ttm', 'TTM'], ['operating_margin_fy', 'FY']]),
					col('FScore', 'Piotroski F-score', 'integer', [['piotroski_f_score_ttm', 'TTM'], ['piotroski_f_score_fy', 'FY']]),
					col('PreTaxMargin', 'Pretax margin %', 'percent', [['pre_tax_margin_ttm', 'TTM']]),
					col('QuickRatio', 'Quick ratio', 'number', [['quick_ratio_fq', 'FQ'], ['quick_ratio_fy', 'FY'], ['quick_ratio_current', 'Current']]),
					col('ResearchNDevelopmentPerEmployee', 'Research and development per employee', 'fundamental', [['research_and_dev_per_employee_fy', 'FY']]),
					col('ResearchNDevelopmentRatio', 'Research and development ratio', 'percent', [['research_and_dev_ratio_ttm', 'TTM'], ['research_and_dev_ratio_fy', 'FY']]),
					col('ReturnOnAssets', 'Return on assets %', 'percent', [['return_on_assets_fq', 'FQ'], ['return_on_assets_fy', 'FY']]),
					col('ReturnOnCapitalEmployed', 'Return on capital employed %', 'percent', [['return_on_capital_employed_fq', 'FQ'], ['return_on_capital_employed_fy', 'FY']]),
					col('ReturnOnCommonEquity', 'Return on common equity %', 'percent', [['return_on_common_equity_ttm', 'TTM'], ['return_on_common_equity_fy', 'FY']]),
					col('ReturnOnEquity', 'Return on equity %', 'percent', [['return_on_equity_fq', 'FQ'], ['return_on_equity_fy', 'FY']]),
					col('ROEAdjustedToBook', 'Return on equity adjusted to book value %', 'percent', [['return_on_equity_adjust_to_book_ttm', 'TTM'], ['return_on_equity_adjust_to_book_fy', 'FY']]),
					col('ReturnOnInvestedCapital', 'Return on invested capital %', 'percent', [['return_on_invested_capital_fq', 'FQ'], ['return_on_invested_capital_fy', 'FY']]),
					col('ReturnOnTangibleAssets', 'Return on tangible assets %', 'percent', [['return_on_tang_assets_fq', 'FQ'], ['return_on_tang_assets_fy', 'FY']]),
					col('ReturnOnTangibleEquity', 'Return on tangible equity %', 'percent', [['return_on_tang_equity_fq', 'FQ'], ['return_on_tang_equity_fy', 'FY']]),
					col('ReturnOnTotalCapital', 'Return on total capital %', 'percent', [['return_on_total_capital_fq', 'FQ'], ['return_on_total_capital_fy', 'FY']]),
					col('RevenuePerEmployee', 'Revenue per employee', 'fundamental', [['revenue_per_employee_fy', 'FY']]),
					col('RevenuePerShare', 'Revenue per share', 'fundamental', [['revenue_per_share_ttm', 'TTM'], ['revenue_per_share_fq', 'FQ'], ['revenue_per_share_fy', 'FY'], ['revenue_per_share_fh', 'FH'], ['revenue_per_share_current', 'Current']]),
					col('SellingGeneralNAdminExpensesRatio', 'Selling, general, and admin expenses ratio', 'percent', [['sell_gen_admin_exp_other_ratio_ttm', 'TTM'], ['sell_gen_admin_exp_other_ratio_fy', 'FY']]),
					col('SharesBuyback', 'Shares buyback ratio %', 'percent', [['share_buyback_ratio_fq', 'FQ'], ['share_buyback_ratio_fy', 'FY']]),
					col('SloanRatio', 'Sloan ratio %', 'percent', [['sloan_ratio_ttm', 'TTM'], ['sloan_ratio_fy', 'FY']]),
					col('SustainableGrowthRate', 'Sustainable growth rate', 'percent', [['sustainable_growth_rate_ttm', 'TTM'], ['sustainable_growth_rate_fy', 'FY']]),
					col('TangibleBookPerShare', 'Tangible book value per share', 'fundamental', [['book_tangible_per_share_fq', 'FQ'], ['book_tangible_per_share_fy', 'FY'], ['book_tangible_per_share_fh', 'FH'], ['book_tangible_per_share_current', 'Current']]),
					col('TobinsQ', 'Tobin\'s Q (approximate)', 'number', [['tobin_q_ratio_fq', 'FQ'], ['tobin_q_ratio_fy', 'FY']]),
					col('TotalAssetsPerEmployee', 'Total assets per employee', 'fundamental', [['total_assets_per_employee_fy', 'FY']]),
					col('TotalDebtPerEmployee', 'Total debt per employee', 'fundamental', [['total_debt_per_employee_fy', 'FY']]),
					col('TotalDebtPerShare', 'Total debt per share', 'fundamental', [['total_debt_per_share_fq', 'FQ'], ['total_debt_per_share_fy', 'FY'], ['total_debt_per_share_fh', 'FH'], ['total_debt_per_share_current', 'Current']]),
					col('TotalDebtToCapital', 'Total debt to capital', 'number', [['total_debt_to_capital_fq', 'FQ'], ['total_debt_to_capital_fy', 'FY']]),
					col('ReceivablesTurnover', 'Total receivables turnover', 'number', [['receivables_turnover_fq', 'FQ'], ['receivables_turnover_fy', 'FY']]),
					col('WorkingCapitalPerShare', 'Working capital per share', 'fundamental', [['working_capital_per_share_fq', 'FQ'], ['working_capital_per_share_fy', 'FY'], ['working_capital_per_share_fh', 'FH'], ['working_capital_per_share_current', 'Current']]),
					col('ZmijewskiScore', 'Zmijewski score', 'number', [['zmijewski_score_ttm', 'TTM'], ['zmijewski_score_fy', 'FY']]),
				],
			},
		],
	},
	{
		id: 'dividends',
		label: 'Dividends',
		sections: [
			{
				columns: [
					col('ContinuousDivGrowth', 'Continuous dividend growth', 'integer', [['continuous_dividend_growth', 'Years']]),
					col('ContinuousDivPayout', 'Continuous dividend payout', 'integer', [['continuous_dividend_payout', 'Years']]),
					col('DividendPayoutRatio', 'Dividend payout ratio %', 'percent', [['dividend_payout_ratio_ttm', 'TTM'], ['dividend_payout_ratio_fy', 'FY'], ['dividend_payout_ratio_percent_fq', 'FQ']]),
					col('DividendsPerShare', 'Dividends per share', 'fundamental', [['dps_common_stock_prim_issue_ttm', 'TTM'], ['dps_common_stock_prim_issue_fq', 'FQ'], ['dps_common_stock_prim_issue_fy', 'FY'], ['dps_common_stock_prim_issue_fh', 'FH']]),
					col('DividendsPerShareGrowth', 'Dividends per share growth %', 'change', [['dps_common_stock_prim_issue_yoy_growth_fy', 'FY YoY']]),
					col('DividendsYield', 'Dividend yield %', 'percent', [['dividends_yield_current', 'TTM'], ['dividends_yield_fy', 'FY'], ['dividends_yield_fq', 'FQ']]),
					col('DividendsYieldForward', 'Dividend yield % (indicated)', 'percent', [['dividends_yield']]),
					col('DividendsPaid', 'Total cash dividends paid', 'fundamental', [['neg_total_cash_dividends_paid_ttm', 'TTM'], ['neg_total_cash_dividends_paid_fq', 'FQ'], ['neg_total_cash_dividends_paid_fy', 'FY'], ['neg_total_cash_dividends_paid_fh', 'FH']]),
				],
			},
		],
	},
];
